# Stating point for a generic python continuous integration pipeline.

name: Python CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
     uses: ./.github/workflows/python_lint.yaml
