# Stating point for a generic python continuous integration pipeline.

name: Python CI

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
     uses: ./.github/workflows/python_lint.yml
