# Starting point for a generic python continuous integration pipeline.

name: Python CI

on:
  workflow_call:
    inputs:
     project_root:
          required: true
          type: string
     mark_inputs:
          required: true
          type: string
     optional_dependencies:
          required: false
          type: string
          default: ''

permissions:
  contents: read

jobs:
  version_check:
    uses: ./.github/workflows/version_check.yaml
    with:
      project_root: ${{ inputs.project_root }}
    # runs-on: ubuntu-latest
    # if: github.ref != 'refs/heads/main'
    # steps:
    # - uses: actions/checkout@v3
    #   with:
    #     ref: 'main'
    # - name: Main Version
    #   run: echo "MAIN_VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_ENV
    # - uses: actions/checkout@v3
    # - name: Merge Version
    #   run: echo "MERGE_VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_ENV
    # - name: Version Comparison
    #   run: python .github/workflows/verify_version.py ${MAIN_VERSION} ${MERGE_VERSION}
  lint:
     uses: ./.github/workflows/python_lint.yaml
     with:
      project_root: ${{ inputs.project_root }}
      optional_dependencies: ${{ inputs.optional_dependencies }}
  unmarked-test:
    uses: ./.github/workflows/unmarked_tests.yaml
    with:
      mark_inputs: ${{ inputs.mark_inputs }}
      optional_dependencies: ${{ inputs.optional_dependencies }}
