name: Python End to End Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  end2end-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: End to end tests with pytest
        uses: ./.github/actions/end2end-tests