# This workflow will enfore code quality using pylint and ruff.

name: Python Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1
      with:
        version: 0.4.10
        args: --extend-select=E

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pylint
      run: python3.10 -m pip install pylint
    - name: Install Dependencies
      run: |
        python3.10 -m pip install .
        python3.10 -m pip install pytest
    # If you do not install dependencies then it will fail PyLint due to import-errors
    - name: Run pylint
      run: pylint .
