name: Unmarked Tests Checker

on:
  workflow_call:
    inputs:
      mark_inputs:
        required: true
        type: string

permissions:
  contents: read

jobs:
  unmarked-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-custom-exit-code
          pip install .
      - name: Capture pytest output
        id: collect_tests
        run: |
          pytest_output=$(pytest --suppress-no-test-exit-code -vv -m "${{ inputs.mark_inputs }}" --collect-only)
          echo "pytest_output<<EOF" >> $GITHUB_ENV
          echo "$pytest_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Checkout ci_python repository
        uses: actions/checkout@v3
        with:
          repository: AFMC-MAJCOM/ci_python
          path: ci_python
          ref: main
      - name: Count and check tests
        id: validate_test_marks
        run: |
          python ci_python/.github/workflows/validate_test_marks.py
        env:
          PYTHON_OUTPUT: ${{ env.pytest_output }}
