name: Unmarked Tests Checker

on:
  workflow_call:
    inputs:
      project_root:
        required: true
        type: string

permissions:
  contents: read

jobs:
  pytest-linux:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # - name: Checkout root project repository
      #   uses: actions/checkout@v3
      #   with:
      #     path: ${{ inputs.project_root }}

      # - name: Checkout ci_python repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: AFMC-MAJCOM/ci_python
      #     path: ci_python
      #     ref: OPAL-756
      # continue-on-error: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-custom-exit-code
          pip install .
      - name: Capture pytest output
        id: collect_tests
        run: |
          pytest_output=$(pytest --suppress-no-test-exit-code -vv -m "not unit and not integration and not end2end" --collect-only)
          echo "pytest_output<<EOF" >> $GITHUB_ENV
          echo "$pytest_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Checkout ci_python repository
        uses: actions/checkout@v3
        with:
          repository: AFMC-MAJCOM/ci_python
          path: ci_python
          ref: OPAL-756
      - name: Count and check tests
        id: validate_test_marks
        run: |
          python ci_python/.github/workflows/validate_test_marks.py
        env:
          PYTHON_OUTPUT: ${{ env.pytest_output }}
