name: Version Check

on:
  workflow_call:
    inputs:
      project_root:
        required: true
        type: string

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Retrieve Project Version
      id: get_version
      run: |
        echo "PROJECT_VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_ENV
        echo "PROJECT_VERSION=${{ env.PROJECT_VERSION }}"
    - name: Version Comparison
      run: python ci_python/.github/workflows/verify_version.py "${{ inputs.main_version }}" "${{ env.PROJECT_VERSION }}"
