name: Version Check

on:
  workflow_call:
    inputs:
      project_root:
        required: true
        type: string

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.project_root }}

    - name: Retrieve Project Version
      id: get_version
      run: |
        echo "PROJECT_VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_ENV
        echo "PROJECT_VERSION=${{ env.PROJECT_VERSION }}"  # For debugging

    - name: Version Comparison
      run: python ci_python/.github/workflows/verify_version.py "${{ inputs.main_version }}" "${{ env.PROJECT_VERSION }}"
