# Starting point for a generic python continuous integration pipeline.

name: Python CI

on:
  workflow_call:
    inputs:
     project_root:
          required: true
          type: string
     mark_inputs:
          required: true
          type: string
     optional_dependencies:
          required: false
          type: string
          default: ''

permissions:
  contents: read

jobs:
  version_check:
    uses: ./.github/workflows/version_check.yaml
    with:
      optional_dependencies: ${{ inputs.optional_dependencies }}

  lint:
     uses: ./.github/workflows/python_lint.yaml
     with:
      project_root: ${{ inputs.project_root }}
      optional_dependencies: ${{ inputs.optional_dependencies }}

  unmarked-test:
    uses: ./.github/workflows/unmarked_tests.yaml
    with:
      mark_inputs: ${{ inputs.mark_inputs }}
      optional_dependencies: ${{ inputs.optional_dependencies }}
